### ISSUE TITLE
Show that Travis reports back build status to the repo

### ISSUE THREAD

**Issue by mrmanc** [MCR-Digital/apprentice-boot-camp-fundamentals-3#11]
Maybe include a screenshot of the status message on GitHub

**Comment by alectunbridge** [comment]
Perhaps highlighting this is sufficient, but I was wondering if telling them how to add each other to their Travis account would be an alternative, to allow them both to see the build status for the shared repository exercises, without having to share a screen to do it.
(This may not even be possible).

**Comment by mrmanc** [comment]
I’ve no idea if that’s possible—I hadn’t considered that they might no be able to see the build. I think if you’re able to push you’re probably able to see the build. Worth testing out and raising a separate issue. The intent of this was to highlight that feature of Travis / GitHub, not to help them to see the status of the build.

**Comment by mrmanc** [comment]
Since there is already a screenshot of the status back in GitHub, I’m going to call this one complete now.
