### ISSUE TITLE
Emphasise that the first exercise is to implement petrol rules only

### ISSUE THREAD

**Issue by alectunbridge** [MCR-Digital/apprentice-boot-camp-fundamentals-3#24]
At time of writing [Exercise Part 4](https://mcr-digital.github.io/apprentice-boot-camp-fundamentals-3/#/13/4) is not explicit enough about only implementing the rules for petrol vehicles, i.e. Story 1.
Several apprentices rushed ahead and implemented all of the rules instead, causing problems for the later exercises.

**Comment by mrmanc** [comment]
Reopening this as I don’t think we’ve resolved the issue.
