### ISSUE TITLE
Exercise about pushing a local branch upstream needs work

### ISSUE THREAD

**Issue by alectunbridge** [MCR-Digital/apprentice-boot-camp-fundamentals-3#25]
The whole [exercise](https://mcr-digital.github.io/apprentice-boot-camp-fundamentals-3/#/31/16) needs looking at, the repository to use, the name of the branch etc all need revising.

**Comment by mrmanc** [comment]
Do you have any more context around this? The exercise is still there, so perhaps this isn’t resolved?

**Comment by mrmanc** [comment]
I think this has been fixed by adding the name of the repo into the slide
