### ISSUE TITLE
C# apprentices had to install dot net core version 2.0.9

### ISSUE THREAD

**Issue by mrmanc** [MCR-Digital/apprentice-boot-camp-fundamentals-3#65]
Not sure what they had installed to start with, but they couldn't run a build to start.

**Comment by mrmanc** [comment]
Not sure whether we should upgrade to 3.1 as [was done in a previous boot camp](https://github.com/MCR-Digital/apprentice-boot-camp-fundamentals-2/commit/ad9d6676cb2bced43a5561776bd0db3e94056ef1). I would make this change myself but I don’t know if the solution file also needs to change.

**Comment by alectunbridge** [comment]
Updated to .NET 6 in f577b6e
